#!/bin/bash
# Copyright 2017 Aleksander Gajewski <adiog@brainfuck.pl>
#   created:  sob, 18 lut 2017, 13:53:28
#   modified: sob, 18 lut 2017, 13:53:36

mkdir -p py/generated/
touch py/generated/__init__.py

(
echo '# This file is an AUTOGENERATED part of beans project.'
echo '# Copyright (c) 2017 Aleksander Gajewski <adiog@quicksave.io>.'
echo ''
echo 'import pybeans'
echo ''
) > py/generated/QsBeans.py

for bean in Tag Item RichItem;
do
    python3 extern/beans/pybeans/generate.py extern/qsbeans ${bean}.json >> py/generated/QsBeans.py
done
